"""Out-of-tree Bunnyland plugin: a calendar of seasonal festivals.

An expansion-pack-sized social pack. A :class:`FestivalConsequence` hangs recurring
festivals on the world clock (spring bloom, high summer, harvest fair, midwinter), opening
and closing them on schedule. Around that calendar it adds decorations, gift-giving,
contests (an open hook other packs plug entries into), and a festive seasonal mood lift.
"""

from .calendar import (
    FESTIVAL_SCHEDULE,
    FestivalClosedEvent,
    FestivalConsequence,
    FestivalDefinition,
    FestivalOpenedEvent,
    active_festival,
    day_of_season,
    festival_fragments,
    scheduled_festival,
)
from .components import ContestComponent, DecorationComponent, FestivalComponent
from .contests import (
    CONTEST_ACTION_DEFINITIONS,
    CONTEST_ACTION_HANDLERS,
    WIN_REPUTATION,
    ContestEnteredEvent,
    ContestEntry,
    ContestJudgedEvent,
    EnterContestHandler,
    JudgeContestHandler,
    ReputationComponent,
    contest_entries,
    contest_fragments,
    register_contest_entry,
    spawn_contest,
)
from .decorations import (
    DECORATION_ACTION_DEFINITIONS,
    DECORATION_ACTION_HANDLERS,
    DecorateHandler,
    RoomDecoratedEvent,
    decoration_fragments,
    room_festivity,
    spawn_decoration,
)
from .enrichment import FestivalGenerationEnricher
from .games import (
    GAME_ACTION_DEFINITIONS,
    GAME_ACTION_HANDLERS,
    PLAY_GAME_DEF,
    WIN_JOY,
    GameBoothComponent,
    GamePlayedEvent,
    Participates,
    PlayGameHandler,
    game_fragments,
    game_roll,
    spawn_booth,
)
from .gifts import (
    GIFT_ACTION_DEFINITIONS,
    GIFT_ACTION_HANDLERS,
    GiftGivenEvent,
    GiveGiftHandler,
)
from .hosting import (
    ATTEND_FESTIVAL_DEF,
    END_FESTIVAL_DEF,
    FESTIVAL_INCIDENT_KIND,
    HOST_FESTIVAL_DEF,
    HOSTING_ACTION_DEFINITIONS,
    HOSTING_ACTION_HANDLERS,
    AttendFestivalHandler,
    AttendsFestival,
    EndFestivalHandler,
    FestivalAttendedEvent,
    FestivalEndedEvent,
    FestivalHostedEvent,
    HostedFestivalComponent,
    HostFestivalHandler,
    Hosts,
    hosted_festivals,
    hosting_fragments,
)
from .install import install_festivalsim
from .mood import SeasonalMoodConsequence
from .plugin import PLUGIN_ID, bunnyland_plugins, plugin
from .spatial import holder_of, room_of
from .spectacle import (
    LAUNCH_FIREWORKS_DEF,
    METEOR_SHOWER,
    SPECTACLE_ACTION_DEFINITIONS,
    SPECTACLE_ACTION_HANDLERS,
    FireworksLaunchedEvent,
    LaunchFireworksHandler,
    MeteorShowerSpectacleConsequence,
    MeteorShowerSpectacleEvent,
    SpectacleComponent,
    meteor_shower_overhead,
    spawn_spectacle,
    spectacle_fragments,
)
from .stage import EXTERNAL_ENTRY_SOURCES, FestivalStageReactor, festival_is_live

__all__ = [
    "ATTEND_FESTIVAL_DEF",
    "CONTEST_ACTION_DEFINITIONS",
    "CONTEST_ACTION_HANDLERS",
    "DECORATION_ACTION_DEFINITIONS",
    "DECORATION_ACTION_HANDLERS",
    "END_FESTIVAL_DEF",
    "EXTERNAL_ENTRY_SOURCES",
    "FESTIVAL_INCIDENT_KIND",
    "FESTIVAL_SCHEDULE",
    "GAME_ACTION_DEFINITIONS",
    "GAME_ACTION_HANDLERS",
    "GIFT_ACTION_DEFINITIONS",
    "GIFT_ACTION_HANDLERS",
    "HOSTING_ACTION_DEFINITIONS",
    "HOSTING_ACTION_HANDLERS",
    "HOST_FESTIVAL_DEF",
    "LAUNCH_FIREWORKS_DEF",
    "METEOR_SHOWER",
    "PLAY_GAME_DEF",
    "PLUGIN_ID",
    "SPECTACLE_ACTION_DEFINITIONS",
    "SPECTACLE_ACTION_HANDLERS",
    "WIN_JOY",
    "WIN_REPUTATION",
    "AttendFestivalHandler",
    "AttendsFestival",
    "ContestComponent",
    "ContestEnteredEvent",
    "ContestEntry",
    "ContestJudgedEvent",
    "DecorateHandler",
    "DecorationComponent",
    "EndFestivalHandler",
    "EnterContestHandler",
    "FestivalAttendedEvent",
    "FestivalClosedEvent",
    "FestivalComponent",
    "FestivalConsequence",
    "FestivalDefinition",
    "FestivalEndedEvent",
    "FestivalHostedEvent",
    "FestivalOpenedEvent",
    "FestivalStageReactor",
    "FestivalGenerationEnricher",
    "FireworksLaunchedEvent",
    "GameBoothComponent",
    "GamePlayedEvent",
    "GiftGivenEvent",
    "GiveGiftHandler",
    "HostFestivalHandler",
    "HostedFestivalComponent",
    "Hosts",
    "JudgeContestHandler",
    "LaunchFireworksHandler",
    "MeteorShowerSpectacleConsequence",
    "MeteorShowerSpectacleEvent",
    "Participates",
    "PlayGameHandler",
    "ReputationComponent",
    "RoomDecoratedEvent",
    "SeasonalMoodConsequence",
    "SpectacleComponent",
    "active_festival",
    "bunnyland_plugins",
    "contest_entries",
    "contest_fragments",
    "day_of_season",
    "decoration_fragments",
    "festival_fragments",
    "festival_is_live",
    "game_fragments",
    "game_roll",
    "holder_of",
    "hosted_festivals",
    "hosting_fragments",
    "install_festivalsim",
    "meteor_shower_overhead",
    "plugin",
    "register_contest_entry",
    "room_festivity",
    "room_of",
    "scheduled_festival",
    "spawn_booth",
    "spawn_contest",
    "spawn_decoration",
    "spawn_spectacle",
    "spectacle_fragments",
]
